import type { ReviewIssue, ReviewSummary, GitHubReviewComment } from '../types/index.js';
import { getDiffPosition } from '../github/service.js';

const SEVERITY_EMOJI: Record<string, string> = {
  Critical: '🔴',
  High: '🟠',
  Medium: '🟡',
  Low: '🔵',
};

const CATEGORY_EMOJI: Record<string, string> = {
  Bugs: '🐛',
  TypeScript: '📘',
  React: '⚛️',
  Performance: '⚡',
  Security: '🔒',
  Architecture: '🏗️',
  CodeQuality: '✨',
  Testing: '🧪',
};

/**
 * Format a single ReviewIssue into a GitHub PR review comment body.
 * Uses GitHub-flavored markdown for readability in the PR interface.
 */
export function formatIssueComment(issue: ReviewIssue): string {
  const severityEmoji = SEVERITY_EMOJI[issue.severity] ?? '⚪';
  const categoryEmoji = CATEGORY_EMOJI[issue.category] ?? '📋';

  const lines: string[] = [
    `${severityEmoji} **${issue.severity}** ${categoryEmoji} **${issue.category}**`,
    '',
    '**Problem**',
    issue.problem,
    '',
    '**Why It Matters**',
    issue.whyItMatters,
    '',
    '**Suggested Fix**',
    issue.suggestedFix,
  ];

  if (issue.improvedCode) {
    lines.push('', '**Improved Code**', '```typescript', issue.improvedCode, '```');
  }

  lines.push('', '> 💡 **Learning Insight**', `> ${issue.learningInsight}`);

  return lines.join('\n');
}

/**
 * Convert ReviewIssues to GitHub review comments with diff positions.
 * GitHub requires "position" (line offset within the diff patch) rather than
 * actual file line numbers. We compute this for each issue.
 */
export function buildGitHubComments(
  issues: ReviewIssue[],
  filePatchMap: Map<string, string>
): GitHubReviewComment[] {
  const comments: GitHubReviewComment[] = [];

  for (const issue of issues) {
    const patch = filePatchMap.get(issue.filePath);

    let position: number | undefined;
    if (patch && issue.line) {
      position = getDiffPosition(patch, issue.line);
    }

    // Only post inline comment if we can find the position
    // Otherwise, the issue will be mentioned in the summary body
    if (position !== undefined) {
      comments.push({
        path: issue.filePath,
        position,
        body: formatIssueComment(issue),
      });
    }
  }

  return comments;
}

/**
 * Build the main review summary body that appears at the top of the GitHub review.
 */
export function buildSummaryBody(
  summary: ReviewSummary,
  issues: ReviewIssue[],
  repo: string,
  prNumber: number
): string {
  const scoreEmoji =
    summary.overallScore >= 8
      ? '🟢'
      : summary.overallScore >= 6
      ? '🟡'
      : summary.overallScore >= 4
      ? '🟠'
      : '🔴';

  const lines: string[] = [
    `## 🤖 AI Code Review Summary`,
    '',
    `**Repository**: \`${repo}\` | **PR**: #${prNumber}`,
    '',
    `### ${scoreEmoji} Overall Score: ${summary.overallScore}/10`,
    '',
    '### Issue Breakdown',
    '',
    '| Severity | Count |',
    '|----------|-------|',
    `| 🔴 Critical | ${summary.criticalCount} |`,
    `| 🟠 High | ${summary.highCount} |`,
    `| 🟡 Medium | ${summary.mediumCount} |`,
    `| 🔵 Low | ${summary.lowCount} |`,
    `| **Total** | **${issues.length}** |`,
    '',
    `**Files Reviewed**: ${summary.filesReviewed}`,
  ];

  if (summary.strengths.length > 0) {
    lines.push('', '### ✅ Strengths');
    for (const s of summary.strengths) {
      lines.push(`- ${s}`);
    }
  }

  if (summary.improvements.length > 0) {
    lines.push('', '### 🔧 Improvement Areas');
    for (const s of summary.improvements) {
      lines.push(`- ${s}`);
    }
  }

  if (summary.learningRecommendations.length > 0) {
    lines.push('', '### 📚 Developer Learning Recommendations');
    for (const r of summary.learningRecommendations) {
      lines.push(`- ${r}`);
    }
  }

  // List any issues that couldn't be posted inline (no diff position)
  const inlineableFiles = new Set(issues.filter((i) => i.line).map((i) => i.filePath));
  const generalIssues = issues.filter((i) => !i.line && !inlineableFiles.has(i.filePath));

  if (generalIssues.length > 0) {
    lines.push('', '### Additional Comments');
    for (const issue of generalIssues) {
      lines.push('', `**\`${issue.filePath}\`** — ${issue.problem}`);
    }
  }

  lines.push(
    '',
    '---',
    '*This review was generated by AI. Always verify suggestions before applying them.*'
  );

  return lines.join('\n');
}
